#!/bin/bash

set -e

ES_JDBC_VERSION=2.1.1.2

wget -q http://xbib.org/repository/org/xbib/elasticsearch/importer/elasticsearch-jdbc/$ES_JDBC_VERSION/elasticsearch-jdbc-$ES_JDBC_VERSION-dist.zip && \
	unzip -q elasticsearch-jdbc-$ES_JDBC_VERSION-dist.zip && \
	rm elasticsearch-jdbc-$ES_JDBC_VERSION-dist.zip

wget -q http://download.microsoft.com/download/0/2/A/02AAE597-3865-456C-AE7F-613F99F850A8/sqljdbc_4.0.2206.100_enu.tar.gz && \
	tar -xzf sqljdbc_4.0.2206.100_enu.tar.gz && \
	mv sqljdbc_4.0/enu/sqljdbc4.jar elasticsearch-jdbc-"$ES_JDBC_VERSION"/lib/ && \
        rm -rf sqljdbc_4.0 && \
        rm sqljdbc_4.0.2206.100_enu.tar.gz
